[package]
name = "dump-events"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
freeswitch-esl-rs = { path = "../../", version = "0.1.0" }